// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQQVZGd3yxyCloa_WMhOqNvv3ez4TBLcg',
    appId: '1:309215213769:web:5962c7c33b6baa82d0f518',
    messagingSenderId: '309215213769',
    projectId: 'fitzone-2500',
    authDomain: 'fitzone-2500.firebaseapp.com',
    storageBucket: 'fitzone-2500.firebasestorage.app',
    measurementId: 'G-N7FP60FKJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANjuOy9UNtxUGnNqYTXX25p0DTAEJNqgI',
    appId: '1:309215213769:android:6803200f4591f9b1d0f518',
    messagingSenderId: '309215213769',
    projectId: 'fitzone-2500',
    storageBucket: 'fitzone-2500.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuENCLrc_ScevTQbT0i9x8AF5Dv0fyxTQ',
    appId: '1:309215213769:ios:06c898a90508937bd0f518',
    messagingSenderId: '309215213769',
    projectId: 'fitzone-2500',
    storageBucket: 'fitzone-2500.firebasestorage.app',
    iosBundleId: 'com.example.fitzoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuENCLrc_ScevTQbT0i9x8AF5Dv0fyxTQ',
    appId: '1:309215213769:ios:06c898a90508937bd0f518',
    messagingSenderId: '309215213769',
    projectId: 'fitzone-2500',
    storageBucket: 'fitzone-2500.firebasestorage.app',
    iosBundleId: 'com.example.fitzoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQQVZGd3yxyCloa_WMhOqNvv3ez4TBLcg',
    appId: '1:309215213769:web:d53dd462c68ebfc5d0f518',
    messagingSenderId: '309215213769',
    projectId: 'fitzone-2500',
    authDomain: 'fitzone-2500.firebaseapp.com',
    storageBucket: 'fitzone-2500.firebasestorage.app',
    measurementId: 'G-3JRCSQ7S2M',
  );
}
